script:
  # - npm test
  # - node_modules/.bin/protractor test/e2e/conf.js
  - npm run test-karma
  - npm run test-protractor
language: node_js
node_js:
  - "0.10"
before_script:
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - webdriver-manager update
  - webdriver-manager start > /dev/null &
  - npm start > /dev/null &
  - http-server > /dev/null &
